### ISSUE TITLE
Is the continuous autoencoder available?

### ISSUE THREAD

**Issue by Paulmzr** [haiciyang/LaDiffCodec#2]
Thanks for your work!
Is the continuous autoencoder (VAE) available?

**Comment by haiciyang** [comment]
Hi, thank you for your interest. Yes we provided checkpoints of continuous AE here - https://indiana-my.sharepoint.com/personal/hy17_iu_edu/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fhy17%5Fiu%5Fedu%2FDocuments%2FResearch%2FLaDiffCodec%2FPretrained%20Checkpoints%2FVersion2. Particularly, you can find the link at README from branch Version 2.
Thank you, Haici

**Comment by Paulmzr** [comment]
Thank you!
